### ISSUE TITLE
Gomega matchers

### ISSUE THREAD

**Issue by coriaedu** [openshift/custom-resource-status#10]
Hi, I started using this library for my Operator, and writing test (https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html) with Ginkgo and the [Gomega matcher library](https://onsi.github.io/gomega/).

I was wondering if there is a library to Gomega-match `Conditions` and `RelatedObjects []corev1.ObjectReference` in tests like:

```go
conditions := getConditions() // returns a []conditions.Condition
Expect(conditions).HaveConditionPresentAndEqual(conditions.ConditionAvailable, corev1.ConditionTrue)) // Just an example, there might be other assertions
//...
//...
Expect(relatedObjects).To(HaveRelatedObjectsSatisfying(
		BeAssignableToTypeOf([]corev1.ObjectReference{}),
		HaveLen(expectedNumberOfRelatedObjects),
		ContainElements(expectedObjectReferences),
		// etc
)))
```

**Comment by djzager** [comment]
Hey @coriaedu , apologies for the delay, did you find the answer you were looking for?

If you have a look in https://github.com/openshift/custom-resource-status/blob/master/testlib/matcher.go you will see that we implement a matcher for conditions. It wouldn't take very much to implement one for relatedObjects also https://onsi.github.io/gomega/#adding-your-own-matchers .

Let me know if there is anything I can do to help.

**Comment by coriaedu** [comment]
Thanks @djzager !   I did solve it with some ad-hoc matchers on my tests. Thanks!
